### ISSUE TITLE
.compare when done only by goldensundown

### ISSUE THREAD

**Issue by banjaxe** [banjaxe/CloudBot#9]
10:34:36 #metal <Goldensundown> .compare banjax
Unhandled exception in thread started by <function run at 0x7f8758706a28>
Traceback (most recent call last):
  File "core/main.py", line 68, in run
    out = func(input.inp, **kw)
  File "plugins/lastfm.py", line 124, in compare
    for item in response["comparison"]["result"]["artists"]["artist"]:
KeyError: 'artist'
10:34:39 #metal <Goldensundown> nooope

**Comment by redanthrax** [comment]
Appears to be working now.
